# Welcome to my page!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Travel Guide Web Site
email: jess.sarbu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
  This website is supposed to help people decide where to go 
  (for vacation or even just 2 days). Don't give up on searching 
  the best place&opportunity. ;)

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


  Tour Guides are responsible for helping people to visit unfamiliar 
  areas. They usually make special trips with groups of tourists 
  in order to show them important places of cities. Their work is 
  ery useful for visitors who are for the first time in some areas, 
  because these professionals are very knowledgeable and provide 
  aluable information to people. They may work in travel agencies
  or museums.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jessicasarbu
github_username:  Jelly17

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
