---
title: Travel Guide Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jess.sarbu@gmail.com
description: 'This website is supposed to help people decide where to go  (for vacation
  or even for just 2 days). Don''t give up on searching  the best place&opportunity.
  ;)

'
baseurl: 
url: 
twitter_username: jessicasarbu
github_username: Jelly17
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
